### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by yzw1** [alibaba/webar.js#5]
我看到你给出的一个几大构建的构成，但是具体怎么运行怎么去操作可以说下嘛，新手刚入手表示无从下手，能解答一下吗

**Comment by Lapsec** [comment]
目前只支持跑在UC浏览器上哦，按package.json里scripts的命令，在本地跑起来就可以了

**Comment by yzw1** [comment]
还是没太懂，给个示例可以吗？顺便问下就是不依靠任何浏览器的、webar市面上有没有

**Comment by yzw1** [comment]
是不是直接npm run build就相当于跑build代指的命令吗

**Comment by yzw1** [comment]
还有给出的index.html直接访问了就出现一个小矩形框什么都没有，你说在本地跑怎么去访问，去运行呢

**Comment by Lapsec** [comment]
WebAR还不是W3C的标准，目前仅有支付宝和UC支持此标准

**Comment by Lapsec** [comment]
需要用UC浏览器访问页面哦

**Comment by yzw1** [comment]
用uc浏览器访问的那个index.html还是什么都没有，也就是一个小矩形框

**Comment by yzw1** [comment]
https://lampnshare.cn/webar.js-master/examples/          
这是那个连接我直接放到服务器上了，在哪访问都是一样，你可以看一下，都是个小矩形

**Comment by Lapsec** [comment]
稍等我也跑一下哈~

**Comment by Lapsec** [comment]
我在本地跑npm run dev是正常的，你再试试？

**Comment by yzw1** [comment]
问句题外话，这个以后发展什么时候可以不局限于浏览器就可以进行操作了呢，你是鱼玩工作室的人吗，找你们个联系方式好难 啊哈哈

**Comment by Lapsec** [comment]
[这个以后发展什么时候可以不局限于浏览器就可以进行操作了呢] 这话题比较广，我们也有一些推进计划。
我们是鱼玩工作室的，进一步联系咱再慢慢斟这话题【xiaosheng.cxs@alibaba-inc.com】
