### ISSUE TITLE
支持的设备

### ISSUE THREAD

**Issue by SeanSure** [alibaba/webar.js#6]
1、现在是安卓和苹果都支持吗？
2、对于安卓是否需要支持ARCORE的手机，苹果ARKIT
3、必须使用标记吗

**Comment by Lapsec** [comment]
1、现在是安卓和苹果都支持吗？
----
是的双端都支持


2、对于安卓是否需要支持ARCORE的手机，苹果ARKIT
----
不需要。也支持接入ARCore和ARkit，这是算法层面的。

3、必须使用标记吗
----
标记是指MarkerDetector么？这是其中一个算法

**Comment by SeanSure** [comment]
有具体的运行实例吗？只有方法没有实例不知道如何拓展呢，谢谢

**Comment by reaper12** [comment]
怎么接入ARCore和ARkit？ @Lapsec

**Comment by Lapsec** [comment]
> 怎么接入ARCore和ARkit？ @Lapsec

需要在Native层做适配。

**Comment by Lapsec** [comment]
> 有具体的运行实例吗？只有方法没有实例不知道如何拓展呢，谢谢

demo暂时没能补充上呢，有兴趣我们私聊。

**Comment by uokivan** [comment]
@Lapsec 想要demo呢, 現在有了嗎？謝謝你
